### ISSUE TITLE
User Story 10: Detail Page

### ISSUE THREAD

**Issue by TammyChen21** [TammyChen21/Capstone-project-little-lucky-finds#18]
## Value Proposition

**As a** ... User
**I want to** be able to see detail information of each product
**so that** I can know everything about the product.  
​

## Description
![Bildschirm­foto 2023-04-07 um 10 39 27](https://user-images.githubusercontent.com/123374532/230575053-4bc575e7-ca97-4661-b80b-f3ad4a6ca862.png)

## Acceptance Criteria

- [ ] Clicking a product from the list shows the detail page
- [ ] The product image is displayed
- [ ] The product title is displayed
- [ ] The product description is displayed
- [ ] The product price is displayed
- [ ] A favorite button is displayed
- [ ] A shopping cart button is displayed
- [ ] Clicking the favorite button add the product to the favorite page
- [ ] Clicking the shopping cart button add the product to the shopping cart page
 ​

## Tasks

- [ ] get detail information of each product with global context
- [ ] list the information on detail page
- [ ] add the link in each product on homepage
      ​

## Complexity

S
